[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc_version = "0.8.26"
evm_version = "cancun"
ffi = true
bytecode_hash = "none"
cbor_metadata = false

[rpc_endpoints]
arbitrum = "https://arb1.arbitrum.io/rpc"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/qxR1LNdvhklKx_2X8JnbnLaFzqinnLrl"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/qxR1LNdvhklKx_2X8JnbnLaFzqinnLrl"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}", chain = "42161" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "11155111" }
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = "1" }
