[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc_version = "0.8.26"
evm_version = "cancun"
ffi = true

[rpc_endpoints]
arbitrum = "https://arb1.arbitrum.io/rpc"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}", chain = "42161", url = "https://api.arbiscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "11155111" }
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = "1" }
